language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

env:
  - REDIS_HOST=0.0.0.0 REDIS_PORT=6379 XDEBUG_MODE=coverage

services:
  - docker

before_install:
  - docker run -d -p 0.0.0.0:6379:6379 --name redis redis:alpine
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install

script:
  - make test